### ISSUE TITLE
Ensure consistent alignment & margins

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/brand#140]
There are a couple issues I've noticed in this category: 

- [x] On the slides where there are two heading text box placeholders, they are overlapping, which makes them hard to click

- [x] On the slide template with 4 dots and text boxes, the text alignment is not vertically centered, so if someone doesn't write enough, it's not aligned with the dot.

- [x] All the slides seem to have a somewhat large left margin as compared to the top margin

- [ ] On the slides that are split, half color, half image, because the margin on the left is so large, the text boxes feel like they come too close to the halfway mark. If consistent margins are kept, the text box is quite narrow (but it is not set like this as a default)

- [x] There is some variation in the top margin between the slides that have 1 and 2 headings

**Comment by AvivaOskow** [comment]
Agree with a lot of these and all find that I feel the left margin is too big most of the time for the content I need to fit so I end up breaking it! So maybe considering making the margin smaller, except on section intro/transition pages, that could maybe stay larger (I'm ok with there being a slightly different margin for those since the content/layout is different, if that doesn't confuse people)

**Comment by cmajel** [comment]
@Dahianna will be investigating this over the next sprint.

**Comment by Dahianna** [comment]
Here's a deck with updated margins: https://docs.google.com/presentation/d/1jBVvqOLrB2NCJR2J_gEspTToeGeAma0DK-jtoocDLzg/edit?usp=sharing

**Comment by cmajel** [comment]
@Dahianna this looks great! 🎉 

I did adjust a few things, but with these adjustments I think we're good to go

* I moved the right box closer in to match the textbox width we have on other slides, and to equal out the space on the right margin.
*Updated*
<img width="650" alt="Screen Shot 2019-06-21 at 2 45 00 PM" src="https://user-images.githubusercontent.com/2374206/59944636-3f6f1c00-9433-11e9-8c50-92ba9c4dff90.png">


* I also adjusted the spacing on the half image / half text boxes to fix the left margin issue raised by @juliaklindpaintner 

*Updated*
<img width="655" alt="Screen Shot 2019-06-21 at 2 45 09 PM" src="https://user-images.githubusercontent.com/2374206/59944617-3716e100-9433-11e9-83e3-b981ccda7add.png">

* I also fixed the alignment of the 1 - 2 - 3 section here so that there were more aligned with the slide title

*Updated*
<img width="809" alt="Screen Shot 2019-06-21 at 2 49 58 PM" src="https://user-images.githubusercontent.com/2374206/59944877-efdd2000-9433-11e9-9dc0-d388762754bf.png">

**Comment by Dahianna** [comment]
Thanks! I'll go ahead and update the template.

**Comment by cmajel** [comment]
@Dahianna I was looking at this again this morning and noticed a fix we should make with  the preheaders:

In the current deck, the preheader rides a lot closer to the title but the text boxes overlap.
*Current master deck*
<img width="763" alt="Screen Shot 2019-07-03 at 9 26 23 AM" src="https://user-images.githubusercontent.com/2374206/60595301-b8943a80-9d74-11e9-80bd-0917136c009a.png">

In [the updated deck](https://docs.google.com/presentation/d/1jBVvqOLrB2NCJR2J_gEspTToeGeAma0DK-jtoocDLzg/edit#slide=id.p17), the text boxes no longer overlap, but the preheader is now much further away:
<img width="857" alt="Screen Shot 2019-07-03 at 9 30 04 AM" src="https://user-images.githubusercontent.com/2374206/60595951-f8a7ed00-9d75-11e9-9c95-9b0386f899db.png">

I did a demo (slide 18) to see if we can fix this alignment without overlapping the boxes, and we can. [Details in slide 18](https://docs.google.com/presentation/d/1jBVvqOLrB2NCJR2J_gEspTToeGeAma0DK-jtoocDLzg/edit#slide=id.g5ca780073e_0_0)!
*Updated*
<img width="781" alt="Screen Shot 2019-07-03 at 9 37 25 AM" src="https://user-images.githubusercontent.com/2374206/60596055-3278f380-9d76-11e9-83a7-2cc29eb15cc7.png">

Could we make this adjustment to the preheaders and then update the master theme?

**Comment by Dahianna** [comment]
Great! I made the updates and new alignments are as follow:

- Preheader: **X** 0.92 **Y** 0.42
- 1 line title: **X** 0.92 **Y** 0.42
- Two line intro statement or title: **X** 0.92 **Y** 0.77
- Paragraph and bulleted list: **X** 0 .92 **Y** 1.33

**Comment by Dahianna** [comment]
Last slide was updated on #172

**Comment by cmajel** [comment]
@Dahianna I mentioned this in #172 but it appears that the demo deck doesn't have the updates applied to the master, which means I could insert a new slide from the layout gallery and get the old alignment.

Menu I am referring to:
<img width="741" alt="Screen Shot 2019-07-10 at 9 12 53 AM" src="https://user-images.githubusercontent.com/2374206/60972154-b17ca780-a2f3-11e9-93df-21b9a8c23ed2.png">


Is this a part of your next step?

**Comment by Dahianna** [comment]
I updated master today. I can update the demo deck as well

**Comment by Dahianna** [comment]
I think this is done, will check during coworking

**Comment by cmajel** [comment]
This is done and announced! 💯 

If future alignment issues come up, please create a separate issue and reference this thread as needed.
