### ISSUE TITLE
Larger icon library

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/brand#141]
I would love to see a larger icon library saved into this template (or better yet, saved to Drive separately). The ones here are useful, but it would be great to have an expanded set either here or somewhere easily accessible.

**Comment by juliaklindpaintner** [comment]
Per @jenniferthibault: Picons should be removed from our decks going forward.

**Comment by cmajel** [comment]
Opening this up to the larger 18F community as we review alternatives to Picons.

Here are the deck icons we currently offer:
![picons-18f-deck--numbered](https://user-images.githubusercontent.com/2374206/57948582-054cb080-78b0-11e9-8b5b-3d0b5da04284.jpg)

Here is helpful feedback that 18Fers can give us feedback on:
- What icons you use all the time?
- What icons you never use?
- What icons we don't have but you would use all the time if we did 

(also, note that we have an ongoing convo in #69 regarding the gender bias of some of our user icons)

**Comment by annepetersen** [comment]
I use a lot of the equivalent of 1, 16, 17 and 28, but can also use emojis to express these. I am surprised by and probably wouldn't use 34 or 35. 

I'd like to note that I hope we never use an icon like 20 again: there are lots of better ways to express part of what this may intend to get across while also being more inclusive and equitable.

**Comment by coreycaitlin** [comment]
![Screen Shot 2019-05-17 at 12 00 39 PM](https://user-images.githubusercontent.com/1450354/57950199-6d44cc00-789b-11e9-8960-33f1782947bb.png)

This is the most common usage of these that I see. As you can see, I sort of gave up on an icon for "procurement" and used the UFO. The concepts we most often need to represent are:

- Agile / being iterative
- Users! and user research! and various _kinds_ of user research
- Communication
- Measurement
- Roadmapping and planning
- DevOps
- Security
- Cloud
- Open source
- Communication

**Comment by juliaklindpaintner** [comment]
I have often reached to the larger picon Sketch library for things like code/coding, handshake, lightbulb, browser, computer, badge, slider controls, eye/glasses, funnel/filter, cloud, open lock, puzzle piece, cloud, brain, microscope, telescope, etc. 

I agree that I often will go to emojis for some of those, but since they don't work when you go into presentation in slides, it's a pain. 

I haven't ever used the snowflake and I don't really like the tablet because it seems pretty specific.

**Comment by austinhernandez** [comment]
I use these whenever FontAwesome doesn't have icons I need that are more illustrative:

Here are some examples of how I've use them!

<img width="636" alt="Screen Shot 2019-05-17 at 2 49 54 PM" src="https://user-images.githubusercontent.com/23194720/57949678-13e89700-78b3-11e9-99a6-6cd6a4c6cc22.png">

<img width="1139" alt="Screen Shot 2019-05-17 at 2 51 51 PM" src="https://user-images.githubusercontent.com/23194720/57949776-5d38e680-78b3-11e9-866c-e14935f42a01.png">

I also know I've used: 27 and 36

**Comment by saraheckert** [comment]
I have never used the gender specific icons, I use 14 primarily.  Not a huge fan of 11, 12, 13, 20, 21 or 22. Never used 24. 34 I have actually used when referring to data centers, as that the the closest icon I thought represented what I needed.

**Comment by cmajel** [comment]
Adding a note recapping slack convos

It would be helpful to have a handshake or something to help show partnership.

**Comment by Jacklynn** [comment]
My feedback on the Material icons are that they're mostly for use in apps and don't do a good job conveying abstract things like processes (Austin's growing tree example or something like icon 15 in the original set). They are also heavier because they're not outlines, if that weighs into your decision to use one or o another.

**Comment by porta-antiporta** [comment]
Is the larger picon library available to 18F at large?  Or is it only limited to specific folks?

**Comment by Jacklynn** [comment]
Have we considered https://feathericons.com/? I just came across it.

**Comment by juliaklindpaintner** [comment]
Oooh @Jacklynn those are great! I wonder if this is what Federalist used for their feather?

**Comment by cmajel** [comment]
@Jacklynn yes! Feather is on the list and its what Federalist uses for icons!

As an update, below are the packs I'm currently reviewing with some quick hit notes - open to suggestions of others. I'll be bringing some more notes to the visual design group next week.

### [Font Awesome](https://fontawesome.com/icons?d=gallery&m=free)

License:  [CC icons / SIL font / MIT code](https://github.com/FortAwesome/Font-Awesome#license)

Pros
* USWDS uses it, a lot of familiarity among designers + devs
* A lot of breadth / icon volume
* Regularly updated 

Cons
* Line icons are harder to come by, skews filled
* Pretty chunky and often heavy, would be a noticeable shift in style for us.

### [Material](https://material.io/tools/icons/?style=baseline)

License: [Apache 2.0](https://material.io/tools/icons/?style=baseline)

Pros
* Lots of icon variety
* Lots of familiarity among designers + devs
* Everything has an outline style
* Lots of icon volume
* Has clear design documentation so that custom icons can be designed

Cons
* Out of date repo
* Names are not always intuitive

### [Material Community](http://materialdesignicons.com/)

License: [Community icons under SIL Open Font License ](https://github.com/Templarian/MaterialDesign#license)

Pros
* Material + community added icons means even more breadth
* Very active repo 
* Have a request-icon feature
* Can become a contributor to possibly contribute back
* Leverages Material design specs

Cons
* Some icons are attributed to Google but not on the Material site, not sure why
* UI is a little clunky, hard to sort for just line icons (but I think they're updating their site soon)


### [Unicons](https://iconscout.com/unicons)

License: [Apache 2.0](https://github.com/iconscout/unicons#license)

Pros:
* Large set of icons
* All line icon style
* Mimics current 18F styles well
* No current design documentation, but it's on their roadmap
* Repo is active / updated in last 3 months
* Have an icon-request feature

Cons
* Not familiar with IconScout, not something used widely
* Relatively new library, git starts in Jan 2019

### [Feather](https://feathericons.com/)
License:[ MIT ](https://github.com/feathericons/feather/blob/master/LICENSE)

Pros:
* Used by Federalist
* Nice delicate line styles, closely matches current 18F styles
* Repo is active / updates made in last 3 months

Cons
* Small library, only ~280 icons

**Comment by cmajel** [comment]
We reviewed our current research and recommendations at the visual design huddle this week:
* [Icon comparison review](https://docs.google.com/presentation/d/1N3ErHfeV2VtsFR-FLjLR-ixXMJ4e8pHFImn22LMEPRE/edit#slide=id.g5942b13c70_1_59) -  including how icons may translate for the "Build these skills" slide from @coreycaitlin 
* [comparison sketch file](https://drive.google.com/drive/folders/12cLQzHGqXNlb6DN9fDjLcGHFoeBLt21O)

Based on the feedback of the group, we'd like to run a pilot using [Feather icons](https://feathericons.com/) for default slide / interaction icons and creating a small set of more detailed, scene-setting icons for print/marketing materials.

_scene-setting example_
<img width="751" alt="Screen Shot 2019-06-06 at 3 47 45 PM" src="https://user-images.githubusercontent.com/2374206/59061868-7d384600-8872-11e9-95bc-1613ef9d3bab.png">

Next steps are to:
- Decide which icons to feature in slides
- Test drive icon replacement on a few key presentations
- Determine 1:1 replacements for 18F website and one-pagers, and present for feedback
- Determine where these icons should live and how other designers can contribute

**Comment by cmajel** [comment]
📣 I've been working on this a bit and am looking for feedback 📣 

I've prepped [some new icon slides](https://docs.google.com/presentation/d/1_al6P1r-_ZW51cg1EvABzutGfAEDeySEvrLA2zoIk3Q/edit#slide=id.g5c72f7ffac_0_23) using [Feather Icons](https://feathericons.com/) as a replacement for Picons. And, I'd like help doing some light stress testing on them. 

Please take a look and take them for a spin in something you are working on.  What I'd like to know is:
* Are these new icons useful/easy to use?
* Is there anything you use all the time that is now missing? Is it in the Feather set or something new?
* Designers - is it easy to find the files you need? Is the documentation provided clear?
* Feedback on these custom icons I have created - do they fit?

<img width="213" alt="Screen Shot 2019-06-26 at 9 43 54 AM" src="https://user-images.githubusercontent.com/2374206/60186147-38f8ef80-97f9-11e9-91a0-1240cfbb7727.png">



## Resources 
[Replacement icon slides](https://docs.google.com/presentation/d/1_al6P1r-_ZW51cg1EvABzutGfAEDeySEvrLA2zoIk3Q/edit#slide=id.g5c72f7ffac_0_23)

[Original FeatherIcons](https://feathericons.com/) - good for downloading editable svgs / searching for names

[PNGs of all FeatherIcons](https://drive.google.com/open?id=15wd-xLnty8d8ZO0Y_nMfV-InPu9_ibLU) - good for nondesigners who just need an icon

[Feather Sketch file](https://drive.google.com/open?id=1DBHB6AJWZ5bKiQQ_vVLGHFV9nVXgDU1b) - includes outlined svgs and symbols for all FeatherIcons, plus the custom icons I have created

[Icon design specs and notes](https://docs.google.com/document/d/1saOzu2t_SZc4ZuV0A5xdB68_Dgy2Ky1-6Xy7I8e5i4w/edit#)


## Preview

<img width="840" alt="Screen Shot 2019-06-26 at 9 39 20 AM" src="https://user-images.githubusercontent.com/2374206/60184623-64c6a600-97f6-11e9-964c-6db24e293771.png">
<img width="842" alt="Screen Shot 2019-06-26 at 9 39 26 AM" src="https://user-images.githubusercontent.com/2374206/60184624-64c6a600-97f6-11e9-8721-70c848bb5469.png">
<img width="843" alt="Screen Shot 2019-06-26 at 9 39 32 AM" src="https://user-images.githubusercontent.com/2374206/60184625-64c6a600-97f6-11e9-8dae-03c3fabbed92.png">

**Comment by Dahianna** [comment]
Here's a test a did based on a deck that used a good number of icons: https://docs.google.com/presentation/d/1e5YWeQAfMDoDKI8SZDTF2APQsXPXxUiFKego2WURvlc/edit?usp=sharing

**Comment by tarunmangukiya** [comment]
Hello Everyone,

I am Tarun Mangukiya, co-founder of [Iconscout](https://iconscout.com). We started [Unicons](https://iconscout.com/unicons) as open source side-project. Iconscout is a design resources marketplace with 1 million+ design resources from 1000+ contributors around the world.

Just found that you guys had discussion regarding Unicons pros and cons a month back. I would like to resolve your concerns and help you to use Unicons.

Cons (as per thread)
- Not familiar with IconScout, not something used widely
- Relatively new library, git starts in Jan 2019

I know you guys are not familiar with Iconscout, as we're new startup from India and on a mission to build best design tools for designer community.
- We started Unicons as a side project in December, 2019 and currently it's being used by 10K+ users around the world.
- We're partnering with open source projects (current in conversation) to provide and help their need of current + custom icons.
- We've line + monochrome style available currently on site.
- Thin-line style that's widely used currently across web, will be launched in Q1 2020. We're open for suggestion of that too.
- We're working on design guidelines but due to time constraints we haven't released it yet.

Feel free to use Unicons for 18F as well as any initiative you're working on. I'll be happy to help you to get started.

Thank you for your time! :)
