### ISSUE TITLE
Create style guidance for illustrations of people

### ISSUE THREAD

**Issue by jenniferthibault** [18F/brand#147]
_Capturing this issue to document an ongoing discussion — the future team should decide if it's the right direction to pursue, adjust as needed, and define next steps._
_____

We started work toward getting more visual consistency in illustrations of human figures across 18F's assets. We were looking for a way to show people what styles to stick to, and ideally give them resources (files, templates, images) to build with.

**Here are use cases we were seeing, and styles we were considering:**

## For small sizes where you don't need all the detail, and a high-level view is a better fit.
@AvivaOskow had used these styles in a presentation and we thought they showed diversity of shape and form. I'm not sure if this style needs attribution or was an original design.

![Train-illustration-2-legend](https://user-images.githubusercontent.com/11636908/54396110-434b0f80-4688-11e9-86cc-ff9bc7d3d171.jpg)

## For larger sizes focusing on facial expressions
We built an [18F-ified](https://drive.google.com/drive/u/0/folders/1MFGWlJ6Z1ZzIVXK0h0Xh8RsUiBZzYdbg) fork of Pablo Stanley's [Avataars](https://avataaars.com/) Library

![18f_avataaar_demo](https://user-images.githubusercontent.com/11636908/54396169-7b525280-4688-11e9-8a60-2eb9abdaa7a6.jpg)

## For active poses with medium/high detail
We considered making an 18F-ified fork of Pablo Stanley's [Humaaans](https://www.humaaans.com/) Library and started basic experiments in this [slide deck](https://docs.google.com/presentation/d/1CLkldsgHmXisuqrHgQKxSuGPMFWhZGVtlMaZBYRsNTI/edit#slide=id.g49e561f260_0_16) about working iteratively

![Screen Shot 2019-03-14 at 6 39 53 PM](https://user-images.githubusercontent.com/11636908/54396190-8dcc8c00-4688-11e9-9683-36c5e8502bc2.png)

![Screen Shot 2019-03-14 at 6 46 46 PM](https://user-images.githubusercontent.com/11636908/54396520-9ffafa00-4689-11e9-9fbf-85524691c661.png)
_____

**Open questions:**
- Will we continue to pursue this direction?
- Where do people to to find this style guidance? (18F identity site, sketch files, drive, etc)

**Comment by cmajel** [comment]
A (late 😬 ) update to this.

We now have the Avataaars as a part of our slide back for use within the team, and a starter for a variety of emotions and types of people:
![Screen Shot 2020-06-11 at 12 37 06 PM](https://user-images.githubusercontent.com/2374206/84415538-e7e83400-abe0-11ea-853a-1c5fbbbaf914.png)

However, I like the idea of continuing to think about ways to get more inclusion into our illustrations, and also to explore options where we can show more situational experiences and body representation rather than focusing just on faces.

Some inspiration on this front:
* [Open peeps](https://www.openpeeps.com/), which includes busts and full body illustrations and customizations for emotion, race, hair, and fashion.
*[ Inspiration from Airbnb](https://airbnb.design/your-face-here/)
