### ISSUE TITLE
Change title slide to be centered vertically, better matching divider slide format

### ISSUE THREAD

**Issue by AvivaOskow** [18F/brand#150]

**Comment by cmajel** [comment]
@AvivaOskow we're going through our list of template updates and want some more info on this. Can you provide more context of what you are looking for? Is it just vertically centering the text?

**Comment by cmajel** [comment]
@AvivaOskow checking back on this - are you talking about vertically centering this title slide:

<img width="890" alt="Screen Shot 2019-05-29 at 10 09 20 AM" src="https://user-images.githubusercontent.com/2374206/58563845-dca2b000-81f9-11e9-9d07-ecc8dbeaef90.png">


To better match these dividers?

<img width="908" alt="Screen Shot 2019-05-29 at 10 10 08 AM" src="https://user-images.githubusercontent.com/2374206/58563908-f6dc8e00-81f9-11e9-92fa-b1ef3da827a9.png">

The title slide alignment is anchored to the top to provide additional space for descriptions and agency logos. I suspect that center aligning it would mean sacrificing that space, so I'm inclined to keep it as is. If you have a sketch of what you're thinking would work better, we're happy to take a look. Otherwise, I can close out this issue.
