### ISSUE TITLE
Rethink large circle bullet points slide

### ISSUE THREAD

**Issue by AvivaOskow** [18F/brand#151]
Slide 12 of template: https://docs.google.com/presentation/d/17DbBdq-hlOWvfEMiCz0Oeg2gZAFDG5NPvgiOAVWrhRw/edit#slide=id.g4eb21fd7af_0_210

Since you can't edit the placement of these, they don't end up being very useful unless your copy stays at 3 lines and 14pt size, which is still pretty small for a presenting slide. The blue circles take up a lot of page real estate too.

Perhaps if they were more spaced out and the text could be larger than 14 pt that would help.

**Comment by cmajel** [comment]
@AvivaOskow one easy fix we could do is extend and adjust the alignment of the text box so that it can go multiple lines.

[Test presentation here (page 12)](https://docs.google.com/presentation/d/17pdMx-byG6x0XTfUMnqTw0mmnJOvhDfeVrTeJQcNsoM/edit?usp=sharing)

<img width="865" alt="Screen Shot 2019-05-29 at 10 51 52 AM" src="https://user-images.githubusercontent.com/2374206/58567199-e6c7ad00-81ff-11e9-9cdf-c582a75bb74f.png">

Since 14px is our base font, I'd like to keep it consistent (though we have it on the list to do a broader evaluation of text sizing for different contexts)

One question I have: Are these meant to register as bullets? Or as icon holders?

**Comment by cmajel** [comment]
@Dahianna the link is updated with the adjusted textbox heights.

**Comment by Dahianna** [comment]
Template has been updated
