### ISSUE TITLE
How to reduce duplicate versions of 18F template when importing theme

### ISSUE THREAD

**Issue by cmajel** [18F/brand#186]
When you import theme, there are multiple versions of the 18F template from un-renamed versions of the deck.

Ideas:
* add a starter slide with renaming instructions / include on identity site
* is there a magic way to give the true master a unique name?
* others?

**Comment by cmajel** [comment]
We've updated the starter slide to include explicit instructions to avoid duplicate decks. At this point, we believe this is our best option.

**Comment by juliaklindpaintner** [comment]
I am afraid this is still a consistent problem I have... When I go to import a theme there are SO many files that show up under 18F Slide Theme_MASTER

![Screen Shot 2020-04-07 at 6 19 15 PM](https://user-images.githubusercontent.com/42982184/78725105-c1fe9480-78fc-11ea-8d13-b5b43889b49d.png)

I now know to look for the ones that don't start with the presentation title slide but with the instructions. I wonder if adding a date to the name of the doc would help? That way those directions could be provided at brand.18f.gov so that folks know to look for the most recent version of the master?
