### ISSUE TITLE
Add blue eyebrow to the master deck design

### ISSUE THREAD

**Issue by Dahianna** [18F/brand#217]
<img width="613" alt="image3" src="https://user-images.githubusercontent.com/22921144/88592795-91b63f80-d02c-11ea-862a-60d7c875ebd3.png">

**Comment by igorkorenfeld** [comment]
@Dahianna  and @cmajel  The blue bar is ready for review on slides [15 & 16](https://docs.google.com/presentation/d/1pLP6EZ-YVvrwMCs7JsWdoYoS-6QOedQqM8GWBlw-q3s/edit#slide=id.g9b410b5f9e_0_24) here. There are other alternatives I tried on the next slides.

After playing with different options and talking with Dahianna last week, I suggest we stick with keep the blue bar above  the title (eyebrow) rather than below (mustache) for two reasons:

1. It'll be difficult keep the bar at a consistent distance from the last line of text if there is more than one line. Although I can attach it to the text box, the text still go past the height of the text box, and then the text box needs to be manually resized. So it will be up to the individual slide creators to size it consistently, or to move the line to the right spot. 

2. Dahianna noted that the bar doesn't work quite as well with two lines of text. That it feels out of place in those situations.


![image](https://user-images.githubusercontent.com/52677065/95516988-283ca080-098e-11eb-83c8-0aae1b8d865f.png)

**Comment by Dahianna** [comment]
They look good to me! @cmajel let us know if you have any changes

**Comment by cmajel** [comment]
I agree about the bar staying on the top and that it will be easier to maintain. 

Looks good to me 👍  Let's add it to the master deck and publicize it / see what feedback we get.

**Comment by Dahianna** [comment]
@igorkorenfeld to look at eyebrow on slides with dark blue background

**Comment by igorkorenfeld** [comment]
@Dahianna and @cmajel here are two example slides. Let me know what you think

![image](https://user-images.githubusercontent.com/52677065/101099106-1c3a1d00-3592-11eb-8dbe-5268623e671d.png)

![image](https://user-images.githubusercontent.com/52677065/101099249-4e4b7f00-3592-11eb-9692-187d5299775a.png)

**Comment by Dahianna** [comment]
Updated in master
