### ISSUE TITLE
Split screen slide template

### ISSUE THREAD

**Issue by Dahianna** [18F/brand#218]
Create a blue split screen and two versions, one 50/50 and another 1/3 - 2/3
<img width="613" alt="image3" src="https://user-images.githubusercontent.com/22921144/88592911-bf9b8400-d02c-11ea-8163-0e72945b7abe.png">

**Comment by cmajel** [comment]
@igorkorenfeld wanted to share that I worked a bit in this format in the [Content Strategy Pitch Deck](https://docs.google.com/presentation/d/1O9_hN4_Q78UgCfcvUV0xO-McbAbRpYfme6Q5W7GyR8A/edit). Some notes:
* Explored a flipped layout where the delivery was to be on specifics/descriptive text first
* Explored heading sizing within the denser / descriptive text areas

**Comment by igorkorenfeld** [comment]
Those look great! The summary/takeaway on darker area works well. Perhaps we could add something like "use the darker half to emphasize or summarize a point" for those slides. 

 It looks like the split layout is just shy of 1/2-1/2, curious if this was intentional or not? 

I thought the typography was also working well. To be clear it's usually 28px, and you bumped it down to 16px with 12px "eyebrow" labels?

**Comment by igorkorenfeld** [comment]
Added to theme
