### ISSUE TITLE
Update Color palette page

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/brand#241]
- [ ] Convert page to markdown
- [ ] Reconfigure or replace contrast table

**Comment by cmajel** [comment]
Moving #245 into here:

---

From our 12/8 sync.

Thinking about [the color matrix ](https://brand.18f.gov/color-palette/), we have a hypothesis that a simpler, row based layout would be easier to scan and rely on less visual interpretation than the current matrix. This issue is here to try and prototype a row based layout similar to the identity site's mobile layout to get feedback on.

Layout notes we discussed:
* Break into sections, with a heading for each background color
* Change the current mobile content to also call out what color combos are _not_ allowed
* Keep the same order for each section
* Incorporate the hex values into the copy. 

Current mobile layout for reference:
![Screen Shot 2020-12-08 at 2 12 46 PM](https://user-images.githubusercontent.com/2374206/101530120-7f93c880-395f-11eb-81c1-96f56eab2383.png)

**Comment by cmajel** [comment]
I explored a row-based layouts that would work within the narrower theme layout, and created the mock below. Some of our considerations:
* Try moving away from a graphic layout to something simpler and more text based. 
* Include the contrast ratios to encourage legitimacy of the graphic, and show the nuance between color combinations. 
* Make it easier for folks to grab hex values from combinations

We asked for [feedback on this mock in #design and #g-accessibility](https://gsa-tts.slack.com/archives/C02AUUQ8R/p1608051456224400) and how it compares to the original grid format. Some of the comments we got:
* The grid is easy to scan and orients folks to color combinations in a logical way.
* Groupings of the rows seemed right.  
* Like having the contrast ratios included
* Consider adding additional information about small text vs large text vs non-text elements and their contrast requirements. 
* Consider switching to a `<table>`

## Mockup

![image](https://user-images.githubusercontent.com/2374206/103686581-0b981080-4f5d-11eb-9c99-e6e6803ccc25.png)


## Original grid
![image](https://user-images.githubusercontent.com/2374206/103687514-62eab080-4f5e-11eb-88ec-b37815f08a61.png)

**Comment by Dahianna** [comment]
We'll move forward with table but we'll create a new issue to look into providing additional info on contrast and image vs. rext

**Comment by igorkorenfeld** [comment]
Posted links and screenshots to Slack for feedback and got some good responses from other designers in the [thread](https://gsa-tts.slack.com/archives/C02AUUQ8R/p1611244231001300?thread_ts=1608051456.224400&cid=C02AUUQ8R)

Folks seemed to prefer the table layout because they found it easier to scan for the information they need. One suggestions was to add an indicator to the table for when non-text elements are OK but small text is not.  

"I’d love to see this page’s intro mention non-text elements. I wonder if there’s a treatment for a table cell item we could use to indicate non-text elements only & put that in the legend. (e.g square w/an icon instead of"

**Comment by igorkorenfeld** [comment]
This will be replaced / augmented by #244, implementation in #252
