### ISSUE TITLE
Resolve "18F Blue" color application issue

### ISSUE THREAD

**Issue by ericronne** [18F/brand#45]

**Comment by ericronne** [comment]
@amberwreed and myself meeting with Hillary to discuss (set for 1.11, awaiting Hillary's meeting confirmation)

**Comment by ericronne** [comment]
- How should #1188FF be applied, if at all?
- What counts as a "standalone" application of the logo?

**Comment by ericronne** [comment]
Still trying to set up a mtg btwn Hillary, Amber, and myself

**Comment by ericronne** [comment]
@quepol @amberwreed 
Hi! I'd love to get fully aligned on how we want to use our blues, so that we can document it, speak with one voice &c &c. Meetings are tricky, so how about we take the conversation in an asynchronous direction here on the git?

Hillary, i know that you wanted to keep 1188ff alive for standalone applications, so for starters, perhaps we should all get aligned on the definition of "standalone." The color doesn't coordinate well with our new palette, which we'd definitely want to apply to our site and places like twitter. Also as points of entry to 18F for so many, they play a key role in our visual branding.

What are your thoughts re standalone applications, etc.? Thx!

Amber, welcome back! Please feel free to add your wisdom, of course :)

**Comment by quepol** [comment]
Hi. I suck at Github. :)

**Comment by amberwreed** [comment]
Thanks for picking this up again Eric! I'd love to chat about colors. I'm a
huge fan of consistency and would love to see us fully transition to our
new brand colors and logo. Let me know what I can do to help out and as
always happy to discuss.



On Fri, Apr 8, 2016 at 11:08 PM, Hillary Hartley <notifications@github.com>
wrote:

> Hi. I suck at Github. :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/brand/issues/45#issuecomment-207716653>
>



-- 
-------------------------
*Amber Reed*
Experience Designer
18F

**Comment by jenniferthibault** [comment]
To recap and close out, this issue had two parts:

 1. What color logo do we use in which contexts?
 2. Does #1188ff exist in the new palette?

In this week's public introduction, we've launched the [revised color palette](https://pages-staging.18f.gov/brand/visual-style/#colors) which does not include #1188ff because it clashes with the rest of the new palette. We understand the 😢 💔  letting it go, but want to focus on creating color combinations that work well with one another, and meet 508 color contrast requirements. We'll continue supporting the questions from rest of the team as we transition away from it.

We are also leading with the primary, black logo and "flooding the landscape with best practices" (to borrow from Noah K in another context) as we introduce a new system. For now we'll use only the black logo, as we figure out design principles for when and how we use the blue and possibly other colors as needed.
