### ISSUE TITLE
Social Media Template

### ISSUE THREAD

**Issue by amberwreed** [18F/brand#57]

**Comment by amberwreed** [comment]
This is a visual template for infographics and quotes to be posted in social media.

**Comment by amberwreed** [comment]
Reference Gov.uk twitter feed

**Comment by goodnightjj** [comment]
<img width="1157" alt="ss 2016-01-27 at 10 16 42 am" src="https://cloud.githubusercontent.com/assets/2229840/12623581/b0adedfa-c4df-11e5-9cf1-b19d16061d89.png">

**Comment by jenniferthibault** [comment]
At a quick glance, I especially like the ones that split the canvas into two and use an icon on one side (bread/clock) These feel unique and "designed" because of the white space and graphic.

**Comment by goodnightjj** [comment]
Using real dummy content to refined and narrowed down the templates. Also, note that all sides of the margins are not the same to allow for best viewing experience on Twitter because the service crops and displays images differently across desktops and mobiles.

<img width="1280" alt="ss 2016-02-01 at 4 23 18 pm" src="https://cloud.githubusercontent.com/assets/2229840/12735864/24a67082-c900-11e5-9fc5-25e02046f125.png">

**Comment by ericronne** [comment]
A few open questions & thoughts.....

 - Could the type be more dramatic? Eg larger heads in some cases.
 - IMO the bright blue KILLS over dark blue. So should we make a rule that we always apply bright blue in some manner to any graphic element that runs over dark blue?
 - The very first layout seems to have an incorrect font for the body type. True?
 - Should we use sketch for these going forward?
 - Who should pick up this issue?

@amberwreed did you have additional thoughts? (also @rtwell and @jenniferthibault too!)

**Comment by jenniferthibault** [comment]
Closing until we observe a need for this in the current organization
