### ISSUE TITLE
Create a repo to collect decks users have created using our templates

### ISSUE THREAD

**Issue by ericronne** [18F/brand#63]
This will inform our ongoing modifications and additions.

**Comment by ericronne** [comment]
One by Alex Pandel:
https://slack-files.com/files-pri-safe/T025AQGAN-F0JJ6GT1S/18f-navy-talentlink-recommendations.pdf?c=1452883660-ed7832def9957cc596e4f476987a0cec80cd4599

**Comment by jenniferthibault** [comment]
In this instance, repo does not = GitHub repository, right? Whatcha thinkin'? Google folder or such?

**Comment by ericronne** [comment]
right, sloppy language sry.
perhaps a Drive folder, but i'm picturing a web page for friendlier access.
i'd say hackpad but you hate it.
if we put it "out there" for all of 18F, we'd want to flag them as unofficial or something, so one user's unfortunate design choices don't spread.

**Comment by jenniferthibault** [comment]
No hackpad!!

I like the idea of linking to them on the site, maybe with two sections: 
1. 18F stock decks (for pitch decks, standard cloud.gov or project case study spiels.) These are decks we (the visual designers) should have involvement in, or should take an existing one that someone started, and whip it into shape.
2. Decks other people have made but aren't our core set. (Consulting one-offs, etc) Just for reference, and you could grab a page or language that's useful.

It would be cool if section 1 could gradually eclipse section 2 entirely, since this isn't meant to be a collection of all decks 18F has ever made, but rather a collection of the styles you might need to build your own.

**Comment by jenniferthibault** [comment]
Now doing this through "best of" examples in an internal team-wide google drive. Closing
