### ISSUE TITLE
Understand use cases for HTML Slides template

### ISSUE THREAD

**Issue by jenniferthibault** [18F/brand#64]
1. Gain a better understanding of how/when/why a user would prefer HTML Slides, Google Slides, and Keynote in order to add guidance to the brand repository about which asset might be the best fit for users when they are looking for templates.
2. Style SCSS for HTML Slides template, learn more about capabilities for having different master slide templates, and build out alternative slides(?)

Examples of HTML Slides:
https://htmldecks.com/
https://htmldecks.com/view/5609ee0b2f5ac30e00bab16a#/
https://github.com/18F/slides
https://github.com/18F/slides/blob/18f-pages/assets/css/theme/source/18f.scss

@vzvenyach can you speak more to the use cases of these slides? How and when someone might choose this over Google/Keynote?

**Comment by vzvenyach** [comment]
Hi @jenniferthibault! So, the reasons I prefer `slides` are as follows:

1. It's just markdown, so I can write what I want to write and not think about presentation (it just works). 
2. It provides a canonical URL for the presentation.
3. It's git-backed, so that I can maintain version control.
4. Because it's markdown based, I can write in my text editor and not the browser or native application.

Is that helpful?

**Comment by jenniferthibault** [comment]
Thanks @vzvenyach , this is great for preliminary understanding. We'll likely follow up with more q's when this is prioritized to a sprint

**Comment by toolness** [comment]
Hey, just wanted to document that I made an initial attempt at a reveal.js-based slideshow here:

https://github.com/18F/18f-reveal.js-theme

It's very much a compromise between reveal's theme CSS/HTML and the awesome Keynote/Google Slides presentation the branding team made, though, so it could use some work. I think @jenniferthibault will be doing some cleanup on it; I'm also happy to help out more with it if needed!

**Comment by jenniferthibault** [comment]
Closing until we observe a need for this in the current organization
