### ISSUE TITLE
font warnings for the Keynote template

### ISSUE THREAD

**Issue by afeld** [18F/brand#66]
When I opened `18F_Template_2016-01-08.key`, I got the following warnings:

![screen shot 2016-01-24 at 6 21 08 pm](https://cloud.githubusercontent.com/assets/86842/12539758/7bf21204-c2c7-11e5-8740-24d48d37c957.png)

Do I need to install the missing fonts? Where would I get them from?

/cc https://github.com/18F/brand/issues/54

**Comment by jenniferthibault** [comment]
Hey @afeld , yep you do need to install the fonts and you can get NimbusSansL (all versions listed) on the staging site here: https://pages-staging.18f.gov/brand/#typography Glad to show you how to install them if you run into any troubles.

We're planning on adding a type specimen to the website so that section sticks out a bit more, right now it's easy to miss.

The warning on Droid Sans IS an real bug though, but the good news is we know about that, and have an issue filed for squashing it: https://github.com/18F/brand/issues/54

**Comment by afeld** [comment]
Looks like there are now instructions to install the fonts. Thanks!
