### ISSUE TITLE
Move off of staging?

### ISSUE THREAD

**Issue by afeld** [18F/brand#83]
https://pages-staging.18f.gov/brand/ has been around for a while now, which is only accessible internally. Is there any reason to not switch to being publicly accessible, using the `18f-pages` branch, which would publish to https://pages.18f.gov/brand/?

**Comment by jenniferthibault** [comment]
Thanks for the ping @afeld 

We're keeping things on staging for now for a few reasons:
1 – we had questions on licensing of this repo and our brand assets. These Q's were sort of resolved, but  we need to make some changes in https://github.com/18F/brand/issues/80 as a result (like adding back in a licensing file and public domain info). We didn't want to make anything publicly available if we didn't fully understand the possible trademark/copyright implications first. I might be able to do this quickly today, but there are a few other points...

2 – The new logo and brand system hasn't been publicly launched yet. We've been using the new presentation template and format, but haven't done a unified logo swap or launch blog post (which is in the works)

3 – mostly, we do not currently have an active contributing team on this project

4 – my hunch is that for now we are most comfortable with this being an internal tool kit for 18F team members building things that look like 18F

These are a few things as I understand them, but @ericronne @amberwreed @rtwell might have other/different thoughts

**Comment by afeld** [comment]
Seems like we're rolling out the branding fully now...good time to make the site public?

**Comment by jenniferthibault** [comment]
Getting there!
From above:

1. Licensing & #80 💥 

2. Launch new logo publicly 💥 

3. Still the case, but not a blocker 🙅 anymore because we had some great front end volunteering the last few weeks on 508 issues

4. Internal-facing: We have issues filed with the writing lab to help us turn this from internal-facing to public-facing. 

 - https://github.com/18F/writing-lab/issues/178
 - https://github.com/18F/writing-lab/issues/177

Thanks for holding us to it :)

**Comment by jenniferthibault** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
TA-DA!!!!!!
https://github.com/18F/brand/tree/18f-pages
https://pages.18f.gov/brand/
