### ISSUE TITLE
Users should be able to easily discover the branded google slides template

### ISSUE THREAD

**Issue by ericronne** [18F/brand#96]
Several 18Fers have become frustrated when searching for the [google slides template](https://docs.google.com/presentation/d/1AtTYOd0jjZnKUhBQ0c5oX5mmHQ4bd_Q2KvrdsQMw2nk/edit#slide=id.p) (cf issue #90, created by @toolness), and left assuming it doesn't yet exist.

In order to make the template more visible, i suggest that we add a button to the [Keynote template section](https://pages-staging.18f.gov/brand/resources/#keynote), change the header / nav to "Slides," and tweak the copy accordingly.

Thoughts, @amberwreed @rtwell @thisisdano @jenniferthibault?

**Comment by jenniferthibault** [comment]
Yes plz. 

We could/should also pull the instructions for finding the Google template out of the PDF and onto the site (which would fall under your copy adjustments, I think).

For later, it would be ideal if we didn't use PDFs at all, since they need to manually be tagged to meet 508 needs. (ours haven't been)

**Comment by jenniferthibault** [comment]
Resolved by https://github.com/18F/brand/pull/97
